[tool.poetry]
name = "trader-quickstart"
version = "0.1.0"
description = "A quickstart for the trader agent for AI prediction markets on Gnosis at https://github.com/valory-xyz/trader"
authors = ["David Vilela <dvilelaf@gmail.com>", "Viraj Patel <vptl185@gmail.com>", "Ojuswi Rastogi <ojuswimail@gmail.com>"]
readme = "README.md"
package-mode = false
packages = []
include = []

[tool.poetry.dependencies]
olas-operate-middleware = { git = "https://github.com/valory-xyz/olas-operate-app.git", rev = "3a26856254e57bff45a7ce1c3daecc7180c63df5", python = ">=3.9,<3.12" }

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
